### ISSUE TITLE
nodejs下的demo是否有错误？

### ISSUE THREAD

**Issue by zhupengfeivip** [yitter/IdGenerator#10]
![image](https://user-images.githubusercontent.com/30720809/131055290-47ac63b9-7844-45b7-8a3c-9e1b4dc9ea38.png)

如上图位置的_IsOverCost是不是应该是Method？

还有nodejs中的部分函数并没有实现，也没有注释，是否未完成？
![image](https://user-images.githubusercontent.com/30720809/131055415-28d81803-c456-4b75-9639-788817780bc0.png)

如上图，

**Comment by yitter** [comment]
问题解决，谢谢提供pr
