### ISSUE TITLE
多线程存在id重复,200并发很容易复现 100多并发偶尔复现,这是我配置的不对吗

### ISSUE THREAD

**Issue by CupidStar** [yitter/IdGenerator#119]
static {
        IdGeneratorOptions options = new IdGeneratorOptions((short)0);
        YitIdHelper.setIdGenerator(options);
    }

    public static long getId(){
        return YitIdHelper.nextId();
    }
    
    @Test
    public void idTest() throws InterruptedException {
        HashSet<Long> set = new HashSet<>();
        int count = 50;
        CountDownLatch countDownLatch = new CountDownLatch(count);
        for (int i = 0; i < count; i++) {
            int finalI = i;
            new Thread(()->{
                for (int j = 0; j < 10; j++) {
                    set.add(IdUtil.getId());
                }
                System.out.println("ok"+ finalI);
                countDownLatch.countDown();
            }).start();
        }
        countDownLatch.await();
        System.out.println(set.size());
    }

**Comment by CupidStar** [comment]
测试用例错了, 多线程下用ConcurrentSkipListSet就没有重复了

public static void main(String[] args) throws InterruptedException {
        ConcurrentSkipListSet<Long> set = new ConcurrentSkipListSet<>();
        int count = 10;
        CountDownLatch countDownLatch = new CountDownLatch(count);
        IdUtil.getId();
        System.out.println("start");
        long start = System.currentTimeMillis();
        for (int i = 0; i < count; i++) {
            new Thread(()->{
                for (int j = 0; j < 2000; j++) {
                    set.add(IdUtil.getId());
                }
                countDownLatch.countDown();
            }).start();
        }
        countDownLatch.await();
        System.out.println(System.currentTimeMillis() - start);
        System.out.println(set.size());
    }

**Comment by MuJianxuan** [comment]
看着是hashset重复问题导致的
