### ISSUE TITLE
提出一些疑问

### ISSUE THREAD

**Issue by bao2314483** [yitter/IdGenerator#13]
1. 如果在不同服务器,部署相同应用,都是采用相同WorkId,会不会导致生成ID重复
2. 如果我想通过一个中心服务统一分配WorkId,实现逻辑是怎样呢,麻烦大佬解答

**Comment by yitter** [comment]
1.会。WorkerId在不同应用实例中不要相同。
2.可以参考这个方案：https://github.com/yitter/IdGenerator/tree/master/Tools/AutoRegisterWorkerId
