### ISSUE TITLE
id生成速度如何优化

### ISSUE THREAD

**Issue by nasodaengineer** [yitter/IdGenerator#24]
看介绍能1s500w到3000w条id，测试看来数量一大还比不上普通的雪花算法
![image](https://user-images.githubusercontent.com/38414302/144972295-96c33eb7-6b73-408f-a256-abc4bbb9d672.png)

**Comment by yitter** [comment]
如果是 50W 的并发请求，可以把 SeqBitLength 设置为 10。
500W的话，建议改为14，TopOverCostCount设置为5000。
