### ISSUE TITLE
C 库没做 C++ 兼容

### ISSUE THREAD

**Issue by lymslive** [yitter/IdGenerator#28]
我是个 C++ 开发，老板推荐使用这个雪花算法。
一开始尝试提供的 C 库，一直链接不成功，后来发现是没写  `extern "C"` 兼容。
标准做法是加上类似如下的宏，使其能同时用于 C 或 C++

```cpp
#ifdef __cplusplus
extern "C" 
{
#endif

// C 库函数 声明

#ifdef __cplusplus
}
#endif
```

另外一个小问题，你这个 C 库的函数接口命名太普通，像 `NextId()` 与 `SetOption()` 之类的函数名太常见，很可能与实际项目其他全局符号冲突，毕竟这个 id 算法库的目的是要集成到某些较大的项目中的。建议不妨统一加上 `yit` 前缀。

**Comment by yitter** [comment]
不少需要 merge 的地方，麻烦再先处理一下
