### ISSUE TITLE
SqlServer雪花函數生成ID重複

### ISSUE THREAD

**Issue by bao2314483** [yitter/IdGenerator#3]
我特意測試了下建立一个Test表,字段有ID,Val两个字段,根据教程把ID字段默认值设置了([dbo].[Fn_NextSnowId](rand()))
然后我执行以下脚本发现总有几十个ID出现重复
```
declare @i int =10000

while @i>0
begin
INSERT INTO [dbo].[Test]([Val])
     VALUES
           ('123')
set @i=@i-1
end 
```

**Comment by yitter** [comment]
你的并发量不小，不建议使用SQL来生成。SQL版本采用了随机数，默认配置下，在同一毫秒下，有1/250的概率相同。
如果你的并发量大，建议加大SQL中的 SeqBigLength ，或者不要采用SQL方法来生成随机数。

**Comment by bao2314483** [comment]
> 你的并发量不小，不建议使用SQL来生成。SQL版本采用了随机数，默认配置下，在同一毫秒有1/250的概率相同。
> 如果你的并发量大，建议加大SQL中的 SeqBigLength ，或者不要采用SQL方法来生成随机数。

我测试过,加大SeqBigLength值为16,效果跟8差别不大

因为这些数据库,不能改动程式,只能动数据库,你意思我明白了,谢谢作者指点
