### ISSUE TITLE
单核跑极限是怎么限制的，我只能跑10w/s

### ISSUE THREAD

**Issue by ankye** [yitter/IdGenerator#38]
step := 200000
		fmt.Println("start")
		t := utils.LocalMilliscond()
		for i := 0; i < step; i++ {
			idgen.NextId()
		}
		fmt.Printf("check total cost %d ms\n", utils.LocalMilliscond()-t)
check total cost 2013 ms

当step设置成100000的时候，耗时是22ms，但是设置200000的时候，耗时就需要2013ms

**Comment by yitter** [comment]
超过5W/s，要修改参数，SeqBitLength改为10（默认6）

**Comment by ankye** [comment]
这个参数可以，非常感谢

**Comment by yitter** [comment]
> > 超过5W/s，要修改参数，SeqBitLength改为10（默认6）
> 
> 作者你好，好奇修改SeqBitLength支持更高并发的话，那为什么会默认6呢

因为SeqBitLength设置为6可以让ID数值更短，另外 5W/s的生成速度，不是一般系统能达到的。所以6是我认为的最佳折中值。
