### ISSUE TITLE
自动注册WorkerId疑问？

### ISSUE THREAD

**Issue by 867824092** [yitter/IdGenerator#39]
按照您提供的自动注册思路，我自己在项目中实现了自动注册WorkerId，数值范围为[1,65535]，当应用程序启动时会根据此范围产生一个随机数，写入到redis(采用了lua脚本来写入保证原子性)，如果已存在会一直尝试创建新的随机数继续写入直到写入成功，程序关闭清除相关key，如果新启动的应用程序随机到了以前生成的随机数值，那么这个时候会不会产生已经生成过的雪花id呢？感觉我这个疑问很滑稽.. 只要时间没有回拨，应该不会重复吧.

**Comment by yitter** [comment]
时间不同，就不会有相同的ID。

**Comment by 867824092** [comment]
> 时间不同，就不会有相同的ID。

谢谢
