### ISSUE TITLE
遇到一个奇怪的问题，hash非常不均匀

### ISSUE THREAD

**Issue by ankye** [yitter/IdGenerator#40]
![image](https://user-images.githubusercontent.com/5154427/189175734-7cb4bc0f-34a7-42f8-9f1a-016ad94623cd.png)

**Comment by ankye** [comment]
user := &model.User{
			UID:      utils.GenUID(),
			AppID:    "aaaa",
			Account:  "",
			Email:    "",
			OpenID:   fmt.Sprintf("%d", utils.GenUID()),
			UUID:     fmt.Sprintf("%d", utils.GenUID()),
			Name:     "name",
			Channel:  "test",
			Avatar:   "avatar",
			Password: fmt.Sprintf("%d", utils.GenUID()),
}

**Comment by yitter** [comment]
可以用ID数值里的时间戳 % 8

**Comment by ankye** [comment]
可以了，但是这样上线后就不能动态修改长度了，只能换另外的hash算法了

**Comment by ankye** [comment]
最近在用kingshard，hash规则不能定义，用id就有问题了

**Comment by liujintaogit** [comment]
id分布不均匀怎么解决

**Comment by liujintaogit** [comment]
怎么解决分布不均匀的问题 等

**Comment by yitter** [comment]
你可以在雪花ID基础上*10+[1,2,3,4,5]的单循环数，然后用尾数做hash。
如果你想在kingshard中，使用整个ID做hash，那要求ID连续，这个做不到。

**Comment by yitter** [comment]
你可以在雪花ID基础上*10+[1,2,3,4,5]的单循环数，然后用尾数做hash。
如果你想在kingshard中，使用整个ID做hash，那要求ID连续，这个做不到。
