### ISSUE TITLE
生成id重复

### ISSUE THREAD

**Issue by lxstream** [yitter/IdGenerator#57]
c# 版本，使用两个线程模拟 程序分布式部署后，生产的雪花id情况
每个线程间隔10 毫秒生成1000个id，会出现很高的重复id，请问参数要怎么配置才不会重复？
 

        private static Queue<(DateTime, long)> _queue = new Queue<(DateTime, long)>();
        private static int _count = 1000;

        static void Main(string[] args)
        {
            var workerId1 = 15;
            var workerId2 = 51;
            Task.Factory.StartNew(() =>
            {
                Run(1, (ushort)workerId1);
            });
            Task.Factory.StartNew(() =>
            {
                Run(1, (ushort)workerId2);
            });
            Task.Factory.StartNew(() =>
            {
                CheckId();
            });
            Console.ReadLine();
        }

        /// <summary>
        /// 运行生成id
        /// </summary>
        /// <param name="method"></param>
        /// <param name="workerId"></param>
        private static void Run(short method, ushort workerId)
        {
            var options = new IdGeneratorOptions()
            {
                Method = method,
                WorkerId = workerId,

                //WorkerIdBitLength = 9,
               // SeqBitLength = 8,
            };

            IIdGenerator idGen = new DefaultIdGenerator(options);
            int count = _count;
            //生成一定数量的id
            while (count > 0)
            {
                _queue.Enqueue((DateTime.Now, idGen.NewLong()));
                //间隔10毫秒
                Task.Delay(10).Wait();
                count--;
            }
        }

        private static void CheckId()
        {
            Console.WriteLine("check start");
            var i = 0;
            var dict = new Dictionary<long, DateTime>();
            int error = 0;
            while (dict.Count < _count)
            {
                while (_queue.TryDequeue(out var item))
                {
                    i++;

                    if (dict.ContainsKey(item.Item2))
                    {
                        error += 1;
                        Console.WriteLine($"{item.Item2} - { item.Item1.ToString("HH:mm:ss fffff")} | {dict[item.Item2].ToString("HH:mm:ss fffff")}");
                    }
                    else
                    {
                        dict.Add(item.Item2, item.Item1);
                    }
                }

                Task.Delay(10).Wait();
            }

            Console.WriteLine($"check end:{error}");
        }

**Comment by yitter** [comment]
IIdGenerator idGen = new DefaultIdGenerator(options);  
这个步骤只能全局一次。
你执行了2次。

**Comment by lxstream** [comment]
两个线程分开执行的，模拟程序部署在两台服务器上

**Comment by lxstream** [comment]
哦，用错队列了 ，谢谢
