### ISSUE TITLE
Duplicate entry '184971260575813' for key 'PRIMARY'

### ISSUE THREAD

**Issue by feng005211** [yitter/IdGenerator#6]
C#使用YitIdHelper.NextId()居然会重复，高频情况下

**Comment by yitter** [comment]
可以把你测试的代码贴一下吗？

**Comment by feng005211** [comment]
注册：
![image](https://user-images.githubusercontent.com/7972139/127109437-a6fe0af8-f012-4be2-bce6-767a3d4f8f51.png)
使用：
![image](https://user-images.githubusercontent.com/7972139/127109577-44542578-bc4d-4d39-bb9e-f5c16557f51e.png)
调用：
![image](https://user-images.githubusercontent.com/7972139/127109614-041bdfbd-7898-4414-a986-e5428b120117.png)

大概出错原因是：在服务运行（高频，但数据量只有1w多）的时候，其他地方调用了AddAsync，导致服务运行完成之后，统一入库时，Id重复

**Comment by feng005211** [comment]
现在我只有2个方案进行处理。
第一个解决Id重复问题，让Id不重复，所以在这里提Issues看看是我的问题，还是什么问题。
第二个就是解决Id重复时能够正常回滚，并且重新运行服务。（这种方法改动有点太大了）

**Comment by yitter** [comment]
> 注册：
> ![image](https://user-images.githubusercontent.com/7972139/127109437-a6fe0af8-f012-4be2-bce6-767a3d4f8f51.png)
> 使用：
> ![image](https://user-images.githubusercontent.com/7972139/127109577-44542578-bc4d-4d39-bb9e-f5c16557f51e.png)
> 调用：
> ![image](https://user-images.githubusercontent.com/7972139/127110138-ec8bd939-c5a6-4715-affe-1fce3f5861ab.png)
> 
> 大概出错原因是：
> 在服务运行（高频，但数据量只有1w多）的时候(使用事务)，其他地方调用了AddAsync（其他地方是直接入库），导致服务运行完成之后，事务统一入库时，Id重复

在应用程序全局范围，YitIdHelper.SetIdGenerator(...) 方法只能被调用一次，否则，会有重复ID。

**Comment by feng005211** [comment]
今天继续出现了这个问题
![image](https://user-images.githubusercontent.com/7972139/127275907-6cbe7f64-f9df-42a9-b087-c6d94f43234e.png)
今天只有2000多数据进行高频生成Id，但是在生成的时候其他线程也插入了一条数据。
![image](https://user-images.githubusercontent.com/7972139/127276154-a2ec1696-77c2-4287-ac08-591cd9d1051e.png)

因为我的服务是在凌晨运行的，所以，冲突了。

**Comment by yitter** [comment]
在应用程序全局范围，YitIdHelper.SetIdGenerator(...) 方法只能被调用一次，否则，会有重复ID。

> 今天继续出现了这个问题
> ![image](https://user-images.githubusercontent.com/7972139/127275907-6cbe7f64-f9df-42a9-b087-c6d94f43234e.png)
> 今天只有2000多数据进行高频生成Id，但是在生成的时候其他线程也插入了一条数据。
> ![image](https://user-images.githubusercontent.com/7972139/127276154-a2ec1696-77c2-4287-ac08-591cd9d1051e.png)
> 
> 因为我的服务是在凌晨运行的，所以，冲突了。

集成时，要遵循一下规则：
1.如果 Insert 数据表的操作来自不同应用服务，请确保各个应用服务内的 WorkerId 不相同。
2.在某个应用服务内，SetIdGenertor 方法，只应该被调用一次。

**Comment by feng005211** [comment]
![image](https://user-images.githubusercontent.com/7972139/127276486-a44a21bc-37f7-45df-8782-c28f24f11433.png)
这个相当于只调用了一次吧？

**Comment by feng005211** [comment]
> 在应用程序全局范围，YitIdHelper.SetIdGenerator(...) 方法只能被调用一次，否则，会有重复ID。
> 
> > 今天继续出现了这个问题
> > ![image](https://user-images.githubusercontent.com/7972139/127275907-6cbe7f64-f9df-42a9-b087-c6d94f43234e.png)
> > 今天只有2000多数据进行高频生成Id，但是在生成的时候其他线程也插入了一条数据。
> > ![image](https://user-images.githubusercontent.com/7972139/127276154-a2ec1696-77c2-4287-ac08-591cd9d1051e.png)
> > 因为我的服务是在凌晨运行的，所以，冲突了。
> 
> 集成时，要遵循一下规则：
> 1.如果 Insert 数据表的操作来自不同应用服务，请确保各个应用服务内的 WorkerId 不相同。
> 2.在某个应用服务内，SetIdGenertor 方法，只应该被调用一次。


我明白了，我应该分离YitIdHelper.SetIdGenerator到每个项目的Application中。

**Comment by feng005211** [comment]
感谢，我已经知道如何做了。注册的时候，应该分应用服务来注册，而不是集中注册。
![image](https://user-images.githubusercontent.com/7972139/127277049-0238885d-412c-4130-a76e-2d07f46212ca.png)
如图所示，对吗？

**Comment by yitter** [comment]
> > 在应用程序全局范围，YitIdHelper.SetIdGenerator(...) 方法只能被调用一次，否则，会有重复ID。
> > > 今天继续出现了这个问题
> > > ![image](https://user-images.githubusercontent.com/7972139/127275907-6cbe7f64-f9df-42a9-b087-c6d94f43234e.png)
> > > 今天只有2000多数据进行高频生成Id，但是在生成的时候其他线程也插入了一条数据。
> > > ![image](https://user-images.githubusercontent.com/7972139/127276154-a2ec1696-77c2-4287-ac08-591cd9d1051e.png)
> > > 因为我的服务是在凌晨运行的，所以，冲突了。
> > 
> > 
> > 集成时，要遵循一下规则：
> > 1.如果 Insert 数据表的操作来自不同应用服务，请确保各个应用服务内的 WorkerId 不相同。
> > 2.在某个应用服务内，SetIdGenertor 方法，只应该被调用一次。
> 
> 我明白了，我应该分离YitIdHelper.SetIdGenerator到每个项目的Application中。

只要在同一个应用实例内，注册一次就可以。

**Comment by yitter** [comment]
> 感谢，我已经知道如何做了。注册的时候，应该分应用服务来注册，而不是集中注册。
> ![image](https://user-images.githubusercontent.com/7972139/127277049-0238885d-412c-4130-a76e-2d07f46212ca.png)
> 如图所示，对吗？

你这是多个应用吗？如果是，就要分开注册，当然，你把注册代码写在一个公共的地方，再被这2个服务分别调用，也是可以的，只是这时，你要确保这2个服务被分配不同的 WorkerId。

**Comment by feng005211** [comment]
OK，感谢您的及时回复。解决了我很大的疑问，现在我会把解决方案分享到交流群里，尤其是Furion下的Admin.NET，作者使用了集中注册，会出大问题。感谢。  可以关闭了

**Comment by yitter** [comment]
Done

**Comment by stephaneThannio** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
Erikevin, @ruipengliu, @zhiweiofli, @liuxiong332, @simon639, @leigaoxing, @Hyiker, @yellowlooks, @wallisyoung, @jordan-johnson-sq, @lf2net089, @jiahuanyu, @theleveragedguess, @Mindzy, @GinChow, @cybercarrot, @bingn, @xuongmaydosi, @Yousefcheng, @deepinwine, @Shiliuang, @WenRichard, @LIUMINGLAN, @liusimonpku, @FlyWay-one, @vzii, @KuJyoAi, @lasting-yang, @miku8miku, @iderekliu, @vlike, @dataCreateMao, @BigtoC, @wwwj27, @Stephen-Xu, @MarineHuang, @CodingSunhj, @leeyo, @nickostendorf, @junessi, @andmeics, @ikunpy, @LongquanLiu, @ourines, @Kennyhrk, @findfz, @wkk88992, @watsonzh, @zhonghua-han, @sunqiang-leobeni001, @codelder, @heduian, @capricornstone, @xiaofeng9527, @newencn, @zz757667, @nicthor, @JefferyTang, @Zhongyangjesse, @estebanhernande, @marvinfurman, @Verkaka, @RoCry, @clark-wu, @534591395, @wen-long, @uire-francis, @duck26, @universeliu, @hrt8881, @wangjunsheng, @f2ngwx, @JadeDragon1988, @zhaozhenxiang, @wangcong1113, @qqjjtt, @sky2code, @chandlerzhang, @HarrylXue, @theajack, @ZhangJunJames, @wjsbjl, @ouliuquan, @TFlay, @jefferson-gif, @pylrichard, @YeYiKong, @xyzgentoo, @WLaoDuo, @edwindannyzhang, @michelyao, @nanlong, @CherishGuo, @chunbin1, @wpj980205, @nickzengcn, @charlesbo, @SvenWenLin, @guilin01

**Comment by andutzu7** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
abyssimth, @ethicnology, @zsjleo, @ERIONKE01, @reyesvicente, @cdevry, @LearnerWu, @Atlasoin, @i4irsh, @manero6, @Elefyqyl, @codingIsCrazy, @laplaceliu, @ellolee, @heiheiheiheiheihei, @baajarmeh, @AyabongaQwabi, @AlexandriaLittle, @Javierchast, @AlirezaSafari7, @latenightz, @luizferrbarbosa, @ANTEVETY, @itsazzad, @Simon-CHOU, @jieruypoe, @apoplepsja, @Yz4230, @mo1ny, @TomLisankie, @cbarraco, @LVtomatoJ, @mitiko, @trailblazingfive, @villivateur, @dreczkaa, @Yinr, @Minamiyama, @RXWatcher, @maddefientist, @Flouse, @t0ster30, @TrevorBagels, @RadonX, @StrawDogs, @wnma3mz, @NullpointerWorks, @gnknithin, @MadReza, @Dont-Copy-That-FloppysTorro, @tru0blu0, @NewRedsquare, @Reclu3e, @pietromenna, @Lycodeboy, @The-Maize, @gamaged, @iranadu, @VenomStyx, @ArchNad, @carson507, @turbodog03, @djangosporti, @Cab789, @Ljqiii, @fatihmert, @sef-ffhs, @Rebell-Leader, @huyld, @Tapuzi, @dbmartins, @ryjen, @naltun, @ChandlerVer5, @chengza, @MinmoTech, @xiaotian044500, @alibakhtiar, @makesmallprogresseveryday, @luckpi, @coloz, @Sunflower-V, @ForumPlayer, @js2xxx, @willxuecn, @ollcp, @TheUltDev, @Y7J4OHen8xnSL, @Gravifer, @luo0427, @xdebron, @M00njuic3, @wdd233, @chentianle10000, @nathanielCherian, @wunai813914, @hychen, @ArchisGokhale, @ferasbg
