### ISSUE TITLE
I'm sorry I'm asking this question here

### ISSUE THREAD

**Issue by nanhui233** [yitter/IdGenerator#62]
Can you send your cso2 .lo file editor again? I really need it, please

**Comment by nanhui233** [comment]
My email is 3433796750@qq.com

**Comment by yitter** [comment]
cso2.lo ? what's that ?

**Comment by nanhui233** [comment]
Is a game's file

**Comment by nanhui233** [comment]
The file is encrypted, but decompiled is a lua file

**Comment by nanhui233** [comment]
All I need now is his decompiler, and LoveBeforT released a repository and he later deleted it, but I need it so much now that I can only ask him

**Comment by nanhui233** [comment]
Can I trouble you to contact him? Thanks
