### ISSUE TITLE
分布式可否提升性能

### ISSUE THREAD

**Issue by Monster0303** [yitter/IdGenerator#64]
go 版本

我想生成 id 位数短一点，经过测试当配置为 WorkerIdBitLength = 2  & SeqBitLength = 3 时，生成 3000 个需耗时 1ms，这能满足现在的需求了

问题：程序是在 pod 中独立运行的，（每个都通过 RegisterOne 注册全局唯一 workerid），当未来需要提高 id 生成速度时，可以通过增加 pod 数量实现吗？并且 id 不重复。比如需要 6000，就将 pod 数量扩容为 2，以此类推（在 WorkerIdBitLength 范围内 range:[0, 3]）

**Comment by yitter** [comment]
WorkerIdBitLength 决定了你的容器运行实例个数，6000的需求，用2可以满足你的需求，未来更高要求，只要增加 WorkerIdBitLength 即可。

**Comment by Monster0303** [comment]
其他配置相同，只要workerid不同，分布式下不同 pod 就一定不会出现重复吗？

**Comment by yitter** [comment]
> 其他配置相同，只要workerid不同，分布式下不同 pod 就一定不会出现重复吗？

是的，分布式环境下，只要 WorkerId 不同，生成的ID不会重复。
