### ISSUE TITLE
PHP make 报错

### ISSUE THREAD

**Issue by Sligcm** [yitter/IdGenerator#80]
语言：PHP，Apple M2 芯片，使用 Docker 容器，容器镜像：php:7.4.33-fpm-alpine3.16， make 的时候报错了。看了下，好像是 pause 这个指令是 intel 平台的，是不是要判断下平台？
/bin/sh /tmp/snowdrift/libtool --mode=compile cc  -I. -I/tmp/snowdrift -DPHP_ATOM_INC -I/tmp/snowdrift/include -I/tmp/snowdrift/main -I/tmp/snowdrift -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /tmp/snowdrift/src/snowflake/spinlock.c -o src/snowflake/spinlock.lo
 cc -I. -I/tmp/snowdrift -DPHP_ATOM_INC -I/tmp/snowdrift/include -I/tmp/snowdrift/main -I/tmp/snowdrift -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /tmp/snowdrift/src/snowflake/spinlock.c  -fPIC -DPIC -o src/snowflake/.libs/spinlock.o
/tmp/ccHfCkKb.s: Assembler messages:
/tmp/ccHfCkKb.s:82: Error: unknown mnemonic `pause' -- `pause'
make: *** [Makefile:197: src/snowflake/spinlock.lo] Error 1

**Comment by yitter** [comment]
问题已修复，请同步代码

**Comment by Sligcm** [comment]
> 问题已修复，请同步代码

已测试，可以了，多谢。

**Comment by Sligcm** [comment]
已测试，可以了，多谢。
