### ISSUE TITLE
WorkerId error. (range:[0, 63]，错误提示

### ISSUE THREAD

**Issue by gulang12** [yitter/IdGenerator#84]
public class ApplicationRunnerInit implements ApplicationRunner {
    private final Logger log = LoggerFactory.getLogger(ApplicationRunnerInit.class);
    @Override
    public void run(ApplicationArguments args) throws Exception {
        // WorkerId：(WorkerId考虑使用redis自增动态分配便于集群部署，每个节点保证唯一)
       
        long workerId = CsRedisUtil.incr(RedisKeyConstant.AppInitData.AUTO_INCREMENT_WORKER_ID, 1);
        IdGeneratorOptions options = new IdGeneratorOptions((short) workerId);
        try {
            // 保存参数（务必调用，否则参数设置不生效）：
            YitIdHelper.setIdGenerator(options);
        }catch (IdGeneratorException idGeneratorException){
            // 失败后，服务停止
            throw new RuntimeException(idGeneratorException.getMessage());
        }
        log.info("[ApplicationRunnerInit]---------current service node workerId:{}",workerId);
    }
}

服务在启动过程中捕获异常，此时 redis中的 WorkerId自增ID值是68，请问这是什么问题
![image](https://github.com/yitter/IdGenerator/assets/26455814/61b7399b-a4a8-4343-bfa3-bd93b921be56)

**Comment by yitter** [comment]
WorkerIdBitLength，默认值为6，决定WorkerId最大值为2^6-1=63。
所以，你要么控制传入的WorkerId不要超过63，要么将参数WorkerIdBitLength设置更大一些，具体规则，参考readme中的【参数设置】。
