### ISSUE TITLE
workid设置问题

### ISSUE THREAD

**Issue by cc-cfg** [yitter/IdGenerator#96]
❄ 如果ID生成需求不超过5W个/s，不用修改任何配置参数

1、ID生成需求不超过5W个/s，是不是写死workid=1 就行？
2、服务A容器化部署后，给服务A的每个pod设置不同的workid目前没找到合适的设置方式，并且pod会变动

**Comment by yitter** [comment]
1. 跟workerid没有关系。
2. 参考：https://github.com/yitter/IdGenerator/tree/master/Tools/AutoRegisterWorkerId

**Comment by yitter** [comment]
> > 1. 跟workerid没有关系。
> > 2. 参考：https://github.com/yitter/IdGenerator/tree/master/Tools/AutoRegisterWorkerId
> 
> 感谢回复，k8s部署的服务A，该服务有5个pod，能否将workId都设置为1，这样出现id冲突的概率大吗？

不能相同，通过官方给的regworkerid组件，基于redis去动态获取。你也可以想办法确保每个容器里的WorkerId唯一。
